# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
project 'BCFunctionTest.xcodeproj'


# 去掉由pod引入的第三方库的警告，需要更新命令才生效
inhibit_all_warnings!

target 'BCFunctionTest' do

    pod 'CBSecp256k1'
    pod 'CBBase58'


end


